Issue: #1115 -listenkomponenten
innoq/innoq-styleguide pull request #83
Opened 2021-02-12 13:49 UTC by daphne90

`::before` wurde durch `::marker` ersetzt und erzeugt an den meisten Stellen noch nicht das richtige Verhalten:

#### Bugs:
-  **unorderd list**: bullet points verschwinden bei allen listeimes, nested elements: falsche farbe (apricot statt blau)
-  **checkd list**: häckchen sind zu dünn und zu weit weg vom content entfernt platziert
-  **ordererd list**: die nummerierung ist zu weit vom content entfernt platziert und für alle Einträge auf 0 gesetzt
- **table of contents**: die pfeile sind komplett weg

2021-06-02 12:30 UTC, nanoparsec requested changes
Schau dir hier nochmal die Spacings der alten Listen an: https://innoq.style/components/detail/list.html
Da muss nochmal ein bisschen nach justiert werden an einigen Stellen.

Bitte überprüfe alle Files, die du geändert hast auf überflüssigen Whitespace und auskommentierten Code, der nicht mehr benötigt wird. Du kannst deinen Editor so konfigurieren, dass er überflussige Zeilen im CSS auch automatisch entfernt ;)

2021-06-02 12:30 UTC, nanoparsec commented on components/05-atoms/text/block/list/_unordered-list.scss
> +.unordered-list {
Die `<ul>` Liste darf keine Klasse haben, das unterstützt unser Markdownparser im CMS nicht.

2021-06-02 12:30 UTC, nanoparsec commented on components/05-atoms/text/block/list/list.html
> +    <ul class = "unordered-list">
s.o. die Klasse muss weg.

2021-06-02 12:30 UTC, nanoparsec commented on components/05-atoms/text/block/list/_checked-list.scss
>        // sass-lint:disable no-vendor-prefixes
Die Zeile kann weg

2021-06-02 12:30 UTC, nanoparsec commented on components/05-atoms/text/block/list/_checked-list.scss
>        @extend %icon;
Ist es auch möglich, Svg Icons hier einzubinden? Aktuell benutzen wir noch teilweise Icons aus einer Iconfont, die aber rausfliegen wird. Dazu zählt auch dieses Icon. Daher müssten wir hier mal klären, ob man auch ein svg einbinden kann. Kannst du das mal recherchieren?

2021-06-02 12:30 UTC, nanoparsec commented on components/05-atoms/text/block/list/_ordered-list.scss
>      position: relative;
Ist das ncoh notwendig?

2021-06-02 12:30 UTC, nanoparsec commented on components/05-atoms/text/block/list/_ordered-list.scss
>          top: -0.23rem;
ist das noch notwendig?

2021-06-02 12:30 UTC, nanoparsec commented on components/05-atoms/text/block/list/_ordered-list.scss
>        position: absolute;
Ist position absolute, relative und die top und left Werte ncoh notwenig?

2021-06-02 12:30 UTC, nanoparsec commented on components/05-atoms/text/block/list/_unordered-list.scss
>    @extend %heading-font-bold;
Hier wird noch nicht die richtige Font angezeigt. Bitt emal checken :)

2021-06-02 12:30 UTC, nanoparsec commented on components/05-atoms/text/block/list/_unordered-list.scss
>          top: 0.73rem; //magic number
Brauchen wir das noch?

2021-06-30 13:03 UTC, daphne90 commented on components/05-atoms/text/block/list/_checked-list.scss
>        @extend %icon;
Ja, über das `content`-Attribut mittels  `url()`-Funtkion + Pfadangabe oder explizite Defintion des svgs. Hier einige Beispiele:  [https://web.dev/css-marker-pseudo-element/](url) Habe z.B das pinke Herz mit 
` content: url("data:image/svg+xml;charset=UTF-8,<svg xmlns='http://www.w3.org/2000/svg' version='1.1' height='24' width='24'><path d='M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z' fill='none' stroke='hotpink' stroke-width='3'/></svg>");` -  ausprobiert und das hat funktioniert.

2021-07-23 14:22 UTC, merged